"""Database model for images generated by ARIA."""
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, LargeBinary, String, Text

from models.conversation import Base


class GeneratedImage(Base):
    __tablename__ = "generated_images"

    id = Column(String, primary_key=True)
    prompt = Column(Text, nullable=False)
    revised_prompt = Column(Text, nullable=True)
    model = Column(String, nullable=False)
    size = Column(String, nullable=False)
    quality = Column(String, nullable=False)
    mime_type = Column(String, nullable=False)
    data = Column(LargeBinary, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
